Feat/register flow
virto-network/virto-connect pull request #4
Opened 2024-11-28 12:49 UTC by ail3ngrimaldi

2025-02-24 12:46 UTC, ail3ngrimaldi commented on index.html
> +    <dialog-virto id="dialog">
Now the component can be added like this:

https://github.com/virto-network/virto-connect/blob/ed8a79c58afd88f26600948666808ffc5be03f4f/index.html#L42-L47

2025-02-24 14:36 UTC, olanod requested changes

2025-02-24 14:36 UTC, olanod commented on index.html
> +        <form username></form>
forms shouldn't be used as "sections", here it would seem 1 form = 1 input but that's not how forms are supposed to work, a form is a collection of inputs/data, if anything we should only have 1 form and as we are abstracting things away a form element is something that can even be hidden away from the user.

Without child elements the component should already give me a default experience or say we require at least an authentication method like password then the password input can be added as child element directly and the component will position it smartly in the shadow root whether it is in a separate page of a wizard or together with other inputs.

2025-02-25 13:57 UTC, ail3ngrimaldi commented on index.html
> +        <form username></form>
Sorry but maybe it needs some explanation. I understand that the forms are not sections, yet the idea here is that, people that want to use virto-connect on their application, have the chance to easily choose a form according to their needs.

If you think that approach is correct, I still think that you are right about adding a default experience.

2025-02-27 05:21 UTC, olanod approved these changes

2025-02-27 05:22 UTC, merged